### ISSUE TITLE
Heyo

### ISSUE THREAD

**Issue by PatrickAlphaC** [othaime-en/decentralized-autonomous-lottery#1]
Just wanted to say thank you for all your help in the 32-hour repository. Really means a lot to me and the whole community. 

Not only that, but you learn so much more helping too :) 

Keep it up, and it will do you well. Feel free to reach out to me in the future if you like!

**Comment by othaime-en** [comment]
Hey @PatrickAlphaC it's been a pleasure helping out. You're right I have learned a tonne of stuff in the process.
About reaching out, would now be a good time asking you to be my mentor? 😄  . I know it's a big ask but I'd really appreciate your wealth of experience. Your humor is top-tier too 😄 I think its underrated.

PS. I've never had a mentor so I don't know if this is the right way to go about this. Looking forward to your response.

**Comment by PatrickAlphaC** [comment]
Flattered you'd like me to be your mentor :) 

Sorry, I'm trying to help as many people as possible, so I wouldn't be able to be your mentor. Helping out in the discussions is a great way to keep learning for you, and you're making amazing progress!

**Comment by othaime-en** [comment]
Hmm... makes sense. Had to try though.
It's okay though to contact you if I have a problem right? something unrelated to the course which I can't post in the discussion forum?

**Comment by PatrickAlphaC** [comment]
What would you not be able to post there?

**Comment by othaime-en** [comment]
Hmm Good point. 
I can't think of something at the moment but I'll let you know if anything arises that may not warrant posting to the discussion.
